### ISSUE TITLE
Minimist crashes with input with double =

### ISSUE THREAD

**Issue by jawline** [substack/minimist#111]
Hi,

If I run the following program

```
var argv = require('minimist')(["--=AAA="]);
console.dir(argv);
```

Minimist crashes.

Stacktrace

```
/Users/pbai002/ExpoSE/Targets/minimist/node_modules/minimist/index.js:102
            var key = m[1];
                       ^

TypeError: Cannot read property '1' of null
    at module.exports (/Users/pbai002/ExpoSE/Targets/minimist/node_modules/minimist/index.js:102:24)
    at Object.<anonymous> (/Users/pbai002/ExpoSE/Targets/minimist/test.js:1:93)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

I know this isn't a valid input but it still probably shouldn't crash.

Cheers

**Comment by YounGoat** [comment]
@jawline I don't think that It is wrong feedback to throw an exception on invalid input. Do you agree that horrible disaster maybe follows if the application continues running in such cases?

However, your suggestion is adopted in my own package [commandos](https://www.npmjs.com/package/commandos). E.g., if you are really prepared for invalid input, you may declare with setting `ingoreInvalidArgument` as `true`:

```javascript
const commandos = require('commandos');
let cmdtext = 'foo --=male --gender=male';
let options = commandos.parse(cmdtext, { ignoreInvalidArgument: true });
```

**Comment by jawline** [comment]
The issue here is more subtle, the regular expression /^--.+=/.test(arg) is more permissive than the capture groups defined in /^--([^=]+)=([\s\S]*)$/ which is used immediately after the first passes, causing a counter intuitive error.

Still, this probably isn't worth fixing so I'll close the issue.
