### ISSUE TITLE
Inconsistent handling of empty values between short and long option forms

### ISSUE THREAD

**Issue by eush77** [substack/minimist#56]
Given this `example.js`:
```js
var minimist = require('minimist');

console.dir(minimist(process.argv.slice(2), {
  alias: {
    format: 'f'
  }
}));
```

Actual output:

```
$ node example.js -f ""
{ _: [ '' ], f: true, format: true }
$ node example.js --format ""
{ _: [], format: '', f: '' }
```

Expected output:
```
{ _: [], format: '', f: '' }
```

The output should at least be the same in both cases.

**Comment by bucaran** [comment]
I don't know if you had your problem fixed, but you can also try [parsec](https://github.com/bucaran/parsec) where this problem is fixed.

**Comment by lydell** [comment]
If you add `string: ['format']` the two outputs will get _closer_ to each other, but the `_` key will still be populated with the empty string.

```
$ cat tst.js
var assert = require('assert')
var parse = require('minimist')

var opts = {
  string: ['foo'],
  alias: {
    'foo': 'f'
  }
}

assert.deepEqual(
  parse(['--foo', '.'], opts),
  parse(['-f', '.'], opts)
)

assert.deepEqual(
  parse(['--foo', ''], opts),
  parse(['-f', ''], opts)
)
~/src/source-map-visualize
$ node tst

assert.js:88
  throw new assert.AssertionError({
        ^
AssertionError: { _: [], foo: '', f: '' } deepEqual { _: [ '' ], f: '', foo: '' }
    at Object.<anonymous> (/home/lydell/src/source-map-visualize/tst.js:16:8)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Function.Module.runMain (module.js:469:10)
    at startup (node.js:124:18)
    at node.js:882:3
```
